image: clever/drone-go:1.7
script:
- make test
publish:
  report_card: {}
  github:
    when:
      branch: master
    script:
    - make release
    artifacts:
    - release
    tag: v$(cat VERSION)
    token: $$github_token
    user: Clever
    repo: gitbot
