image: clever/drone-go:1.5
script:
  - make test
publish:
  github:
    when:
      branch: master
    script:
      - make release
    artifacts:
      - release
    tag: v$(cat VERSION)
    token: $$github_token
    user: Clever
    repo: gitbot
