repos:
  - "git@github.com:Clever/gitbot.git"
change_cmd:
  path: "./add_license.sh"
post_cmds:
  - path: "git"
    args: ["push", "-f", "origin", "HEAD:add-license"]
  - path: "hub"
    args: ["pull-request", "-m", "Add license", "-b", "Clever:master", "-h", "Clever:add-license"]
